[changelog]
header = ""
body = """
{% if version %}\
## {{ version | trim_start_matches(pat="v") }}
{% else %}\
## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message | upper_first }}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
commit_parsers = [
  { message = "^feat", group = "🚀 Features" },
  { message = "^fix", group = "🐛 Fixes" },
  { message = "^docs", group = "📝 Documentation" },
  { message = "^(refactor|perf)", group = "🧹 Refactor" },
  { message = "^test", group = "🧪 Tests" },
  { message = "^ci", group = "⚙️ CI" },
  { message = ".*", group = "Other" },
  { message = "^chore", skip = true },
  { message = "^bump", skip = true },
  { message = "^\\d+\\.\\d+\\.\\d+$", skip = true },
]
commit_preprocessors = [
  { pattern = "\\[BRANCH\\]", replace = "" },
  { pattern = "^\\d+\\.\\d+\\.\\d+\\s*", replace = "" },
]
protect_breaking_commits = false
filter_commits = false
sort_commits = "oldest"